name: Generate pgEdge SBOM
description: Downloads a pgEdge tarball, generates SBOMs and vulnerability report.
author: maqeel75

inputs:
  pg_tarball_url:
    description: "URL to the pgEdge tarball"
    required: false
    default: "https://pgedge-download.s3.amazonaws.com/REPO/pg17-17.5-1-amd.tgz"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.pg_tarball_url }}

